jhipster-dev-postgresql:
  container_name: clinic-dev-postgresql
  image: postgres
  # volumes:
  # - ~/volumes/jhipster/clinic/dev-postgresql/:/var/lib/postgresql/
  environment:
  - POSTGRES_USER=clinic
  - POSTGRES_PASSWORD=
  ports:
  - "5432:5432"

